import {
  Activity,
  AlertTriangle,
  Anchor,
  BarChart3,
  Bell,
  BookOpen,
  Box,
  Boxes,
  Brain,
  Bug,
  Calendar,
  Calculator,
  Camera,
  CheckCircle2,
  Clock,
  Coffee,
  Compass,
  Cpu,
  Database,
  DollarSign,
  Eye,
  Feather,
  FileText,
  FileCode2,
  Filter,
  Flag,
  Folder,
  Gift,
  Globe,
  GraduationCap,
  Hammer,
  Heart,
  Home,
  Layers,
  LineChart,
  Lightbulb,
  Lock,
  Mail,
  Map as MapIcon,
  Music,
  Package,
  PieChart,
  Play,
  Plug,
  Rocket,
  Save,
  Search,
  Settings,
  Shield,
  ShoppingCart,
  Sparkles,
  Star,
  Sun,
  Tag,
  Target,
  TerminalSquare,
  Trash2,
  TrendingUp,
  Trophy,
  Users,
  Wand2,
  Wrench,
  Zap,
  type LucideIcon,
} from "@/lib/icons"

export interface IconGlyph {
  key: string
  label: string
  icon: LucideIcon
  category: "data" | "action" | "object" | "misc"
}

// Polite subset — enough variety for users to find a glyph, not so much
// the picker feels overwhelming.
export const ICON_GLYPHS: IconGlyph[] = [
  // data
  { key: "database", label: "Database", icon: Database, category: "data" },
  { key: "boxes", label: "Stack", icon: Boxes, category: "data" },
  { key: "layers", label: "Layers", icon: Layers, category: "data" },
  { key: "package", label: "Package", icon: Package, category: "data" },
  { key: "folder", label: "Folder", icon: Folder, category: "data" },
  { key: "filter", label: "Filter", icon: Filter, category: "data" },
  { key: "tag", label: "Tag", icon: Tag, category: "data" },
  // charts
  { key: "bar", label: "Bar chart", icon: BarChart3, category: "data" },
  { key: "line", label: "Line chart", icon: LineChart, category: "data" },
  { key: "pie", label: "Pie chart", icon: PieChart, category: "data" },
  { key: "chart", label: "Chart", icon: BarChart3, category: "data" },
  { key: "trending", label: "Trending", icon: TrendingUp, category: "data" },
  { key: "activity", label: "Activity", icon: Activity, category: "data" },
  // action
  { key: "play", label: "Run", icon: Play, category: "action" },
  { key: "search", label: "Search", icon: Search, category: "action" },
  { key: "wand", label: "Magic", icon: Wand2, category: "action" },
  { key: "sparkles", label: "Sparkle", icon: Sparkles, category: "action" },
  { key: "save", label: "Save", icon: Save, category: "action" },
  { key: "rocket", label: "Rocket", icon: Rocket, category: "action" },
  { key: "zap", label: "Zap", icon: Zap, category: "action" },
  { key: "lightbulb", label: "Idea", icon: Lightbulb, category: "action" },
  { key: "hammer", label: "Build", icon: Hammer, category: "action" },
  { key: "wrench", label: "Tune", icon: Wrench, category: "action" },
  // object
  { key: "users", label: "Users", icon: Users, category: "object" },
  { key: "shopping", label: "Orders", icon: ShoppingCart, category: "object" },
  { key: "dollar", label: "Money", icon: DollarSign, category: "object" },
  { key: "calendar", label: "Time", icon: Calendar, category: "object" },
  { key: "clock", label: "Clock", icon: Clock, category: "object" },
  { key: "file-text", label: "Doc", icon: FileText, category: "object" },
  { key: "file-code", label: "Code", icon: FileCode2, category: "object" },
  { key: "globe", label: "Global", icon: Globe, category: "object" },
  { key: "map", label: "Map", icon: MapIcon, category: "object" },
  { key: "mail", label: "Mail", icon: Mail, category: "object" },
  { key: "book", label: "Book", icon: BookOpen, category: "object" },
  { key: "target", label: "Target", icon: Target, category: "object" },
  { key: "flag", label: "Flag", icon: Flag, category: "object" },
  { key: "shield", label: "Shield", icon: Shield, category: "object" },
  { key: "lock", label: "Lock", icon: Lock, category: "object" },
  { key: "bell", label: "Alert", icon: Bell, category: "object" },
  { key: "bug", label: "Bug", icon: Bug, category: "object" },
  { key: "brain", label: "Brain", icon: Brain, category: "object" },
  // misc
  { key: "compass", label: "Compass", icon: Compass, category: "misc" },
  { key: "terminal", label: "Terminal", icon: TerminalSquare, category: "misc" },
  { key: "settings", label: "Settings", icon: Settings, category: "misc" },
  { key: "cpu", label: "CPU", icon: Cpu, category: "misc" },
  { key: "calc", label: "Calc", icon: Calculator, category: "misc" },
  { key: "star", label: "Star", icon: Star, category: "misc" },
  { key: "trophy", label: "Trophy", icon: Trophy, category: "misc" },
  { key: "heart", label: "Heart", icon: Heart, category: "misc" },
  { key: "music", label: "Music", icon: Music, category: "misc" },
  { key: "sun", label: "Sun", icon: Sun, category: "misc" },
  { key: "coffee", label: "Coffee", icon: Coffee, category: "misc" },
  { key: "feather", label: "Feather", icon: Feather, category: "misc" },
  { key: "home", label: "Home", icon: Home, category: "misc" },
  { key: "camera", label: "Camera", icon: Camera, category: "misc" },
  { key: "anchor", label: "Anchor", icon: Anchor, category: "misc" },
  { key: "alert", label: "Alert", icon: AlertTriangle, category: "misc" },
  { key: "check", label: "Check", icon: CheckCircle2, category: "misc" },
  { key: "graduation", label: "Cap", icon: GraduationCap, category: "misc" },
  { key: "trash", label: "Trash", icon: Trash2, category: "misc" },
  { key: "plug", label: "Plug", icon: Plug, category: "misc" },
  { key: "eye", label: "Eye", icon: Eye, category: "misc" },
  { key: "gift", label: "Gift", icon: Gift, category: "misc" },
  { key: "box", label: "Box", icon: Box, category: "misc" },
]

export const ICON_GLYPH_MAP = new Map<string, IconGlyph>(ICON_GLYPHS.map((g) => [g.key, g]))

export const ICON_COLOR_OPTIONS: { key: string; value: string }[] = [
  { key: "teal",   value: "oklch(76% 0.14 195)" },
  { key: "green",  value: "oklch(74% 0.18 145)" },
  { key: "amber",  value: "oklch(80% 0.16 85)" },
  { key: "violet", value: "oklch(74% 0.18 295)" },
  { key: "pink",   value: "oklch(74% 0.18 350)" },
  { key: "red",    value: "oklch(70% 0.22 25)" },
  { key: "blue",   value: "oklch(76% 0.13 245)" },
  { key: "lime",   value: "oklch(80% 0.18 130)" },
]

export function iconFor(key: string | undefined): LucideIcon {
  if (!key) return Boxes
  return ICON_GLYPH_MAP.get(key)?.icon ?? Boxes
}
